version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - json-server

  json-server:
    image: typicode/json-server
    volumes:
      - ./db.json:/data/db.json
    command: json-server --watch /data/db.json --host 0.0.0.0 --port 3001
    ports:
      - "3001:3001"
